#!/bin/sh

if [ -x $(which syncthing) ]; then
        if (curl http://127.0.0.1:8384/rest/system/ping); then
                pkill syncthing
        else
                syncthing serve --no-browser
        fi
fi
