#!/bin/sh

# made by shit gippity

if [ "$#" -eq 0 ]; then
  echo "Usage: $0 <command>"
  exit 1
fi

COMMAND="$@"

eval "$COMMAND"

while :; do
  echo "Press Enter to repeat: $COMMAND"
  read a
  eval "$COMMAND"
done
