#!/bin/sh

# made by shit gippity

if [ "$#" -eq 0 ]; then
  echo "Usage: repeat_clear <command>"
  exit 1
fi

COMMAND="$*"

while :; do
  clear
  eval "$COMMAND"
  echo -n $(tput bold)Press Enter to repeat: $(tput setaf 3)$COMMAND $(tput sgr0)
  read a
done
