#!/usr/bin/env bash
instances=("MCSR\ 1.16.1" "MCSR\ Ranked")

# DO NOT add a '/' at the end of launcher_prefix's value
launcher_prefix=~/.local/share/PrismLauncher/instances
for inst in ${instances[@]}; do
    rm -r $launcher_prefix/$inst/minecraft/saves/Random*
    rm -r $launcher_prefix/$inst/minecraft/saves/New*
    rm -r $launcher_prefix/$inst/minecraft/saves/mcsrranked*
done
