#!/bin/sh

# https://unix.stackexchange.com/questions/520597/how-to-reduce-the-size-of-a-video-to-a-target-size

# Check if correct number of arguments are passed
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input> <target_size_in_MB> [output]"
    exit 1
fi

input_file="$1"
target_size_MB="$2"
output_file="${3:-${input_file%.*}_${target_size_MB}mb.mp4}"
echo $output_file

# Calculate duration of the input video
duration=$(ffprobe -i "$input_file" -show_entries format=duration -v quiet -of csv="p=0")
duration_round_up=$((${duration%.*} + 1))

# Calculate target bitrate
target_bitrate=$(((target_size_MB * 8 * 1000 * 1000) / $duration_round_up))

# Compress video using ffmpeg
ffmpeg -i "$input_file" -b:v "$target_bitrate" -minrate "$target_bitrate" -maxrate "$target_bitrate" -bufsize "$((target_bitrate / 2))" "$output_file"
