#!/bin/sh
# $(which emacsclient) --socket-name=/tmp/emacs$(id -u)/server --create-frame --alternate-editor=$(which emacs) $@ &
# $(which emacsclient) --socket-name=/tmp/emacs$(id -u)/server --create-frame --alternate-editor=$(which emacs) $@ &
$(which emacsclient) --create-frame --alternate-editor=$(which emacs) $@ &
