#!/bin/sh
sesh list -i -H | fzf-tmux -e --ansi -p 80%,80% \
        --no-sort --border-label " ${1:-sesh} " --prompt '⚡ ' \
        --header '  ^a all ^t sessions ^f find ^k kill selected session ^r root' \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-a:change-prompt(⚡ )+reload(sesh list -iH)' \
        --bind 'ctrl-t:change-prompt(  )+reload(sesh list -it)' \
        --bind 'ctrl-f:change-prompt(  )+reload(bfs -type d -printf %P\n)' \
        --bind 'ctrl-k:execute(tmux kill-session -t $(echo {} | cut -c 5-))+change-prompt(⚡ )+reload(sesh list -iH)' \
        --bind 'ctrl-r:execute(sesh connect --root .)' \
        --preview-window 'right:55%' \
        --preview 'sesh preview {}'
# https://github.com/junegunn/fzf/issues/3817

# use the `sa or sc` command for joining a folder without tmenu

# --bind 'ctrl-f:change-prompt(  )+reload(eza -1aD --sort=modified --icons=always)' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -Htd -cnever)' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -H -cnever --type d | sed "s|^\./||")' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -H -cnever --type d -x stat --format "%Y %n" | cut -d" " -f2- | sed "s|^\./||")' \
# --bind 'ctrl-l:execute(sesh last)+abort'
# --bind 'ctrl-f:change-prompt(  )+reload(fd -td --absolute-path | sed -E "s|$HOME|~|g; s|.*|\x1b[36m \x1b[0m&\x1b[0m|")' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -td --absolute-path | sed -E "s|$HOME|~|g; s|.*|\x1b[36m \x1b[0m&\x1b[0m|")' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -td -a | sed "s|$HOME|~|g")' \
