#!/usr/bin/env bash

history_file="$HOME/.local/share/dmenu-calc/history"

get_history() {
    [[ ! -f $history_file ]] && mkdir -p $(dirname $history_file) && touch $history_file
    [[ ! -s $history_file ]] && echo "No history found" || tac $history_file
}

is_in_history() { grep -q -x -F "$1" $history_file; }

add_to_history() { echo "$1" >>$history_file; }

copy_to_clipboard() { printf "$1" | wl-copy; }

result_from_equation() { printf "$1" | sed 's/^.*\(=\|≈\) //'; }

main() {
    # dmenu_cmd="tofi -l 10 -p"
    dmenu_cmd="tofi --font /nix/store/4gy27bkanihhcc96v45vqslvbkvii1i5-aporetic-sans-mono-1.2.0/share/fonts/truetype/aporetic-sans-mono-normalbolditalic.ttf --prompt-text=Calculator: --require-match=false"

    while
        input=$(get_history | ${dmenu_cmd} "$@")
        [[ -n $input ]] # quit == no input
    do
        equation=$(is_in_history "$input" && echo "$input" || echo "$(qalc $input)")

        add_to_history "$equation"
        copy_to_clipboard $(result_from_equation "$equation")
    done
}

main "$@"
