#!/bin/sh

DIRECTORY=$1

if [ ! -n "$DIRECTORY" ]; then
        exit 1
fi

if [ ! -d "$DIRECTORY" ]; then
        mkdir $DIRECTORY
fi

[ ! -n "$TMUX" ] && {
        sesh connect $DIRECTORY
        return
}

prev_session=$(tmux display-message -p '#S')

sesh connect "$DIRECTORY" || return
if [ "$DIRECTORY" != "" ]; then
        tmux kill-session -t "$prev_session"
fi
