#!/bin/sh

out=$1

if [ ! -n "$out" ]; then
        exit 1
fi

if [ ! -d "$out" ]; then
        mkdir $out
fi

[ ! -n "$TMUX" ] && {
        sesh connect $out
        return
}

prev_session=$(tmux display-message -p '#S')

sesh connect "$out" || return
if [ -n "$out" ] && [ "$out" != "$prev_session" ] && [ "$(echo "$out" | cut -c 5-)" != "$prev_session" ]; then
        tmux kill-session -t "$prev_session"
fi
