#!/bin/sh
# t is just this script without the kill-session
if [ ! -n "$TMUX" ]; then
	exec t
fi

prev_session=$(tmux display-message -p '#S')
out=$(tmenu "sesh relinquish")

sesh connect "$out" || return

if [ -n "$out" ] && [ "$out" != "$prev_session" ] && [ "$(echo "$out" | cut -c 5-)" != "$prev_session" ]; then
	tmux kill-session -t "$prev_session"
fi
