#!/bin/sh
TRANSFORMER='
  echo -n change-preview-window:
  if ((100 * FZF_COLUMNS / FZF_LINES >= 150)) && ((FZF_COLUMNS >= 120)); then
    echo "right,50%,border-left"
  elif ((FZF_LINES >= 40)); then
    echo "up,30%,border-bottom"
  else
    echo "hidden"
  fi
'

sesh list -i -H | fzf-tmux -e --ansi -p 80%,80% \
  --no-sort --border-label " ${1:-sesh} " --prompt '⚡ ' \
  --header '  ^a all ^t sessions ^f find ^k kill selected session ^r root' \
  --bind 'tab:down,btab:up' \
  --bind 'ctrl-a:change-prompt(⚡ )+reload(sesh list -iH)' \
  --bind 'ctrl-t:change-prompt(  )+reload(sesh list -it)' \
  --bind 'ctrl-f:change-prompt(  )+reload(ls -D1)' \
  --bind 'ctrl-k:execute(tmux kill-session -t $(echo {} | cut -c 5-))+change-prompt(⚡ )+reload(sesh list -iH)' \
  --bind 'ctrl-r:execute(sesh connect --root .)' \
  --bind "start:transform($TRANSFORMER),resize:transform($TRANSFORMER)" \
  --preview-window 'right:55%' \
  --preview 'sesh preview {}'
# https://github.com/junegunn/fzf/issues/3817

# --bind 'ctrl-f:change-prompt(  )+reload(fd -H -cnever --type d | sed "s|^\./||")' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -H -cnever --type d -x stat --format "%Y %n" | cut -d" " -f2- | sed "s|^\./||")' \
# --bind 'ctrl-l:execute(sesh last)+abort'
# --bind 'ctrl-f:change-prompt(  )+reload(fd -Htd -cnever)' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -td --absolute-path | sed -E "s|$HOME|~|g; s|.*|\x1b[36m \x1b[0m&\x1b[0m|")' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -td --absolute-path | sed -E "s|$HOME|~|g; s|.*|\x1b[36m \x1b[0m&\x1b[0m|")' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -td -a | sed "s|$HOME|~|g")' \
# --bind 'ctrl-f:change-prompt(  )+reload(fd -td)' \
