#!/bin/sh
cd ~/.nix &&
        git add . &&
        (git diff --cached --quiet ||
                (git commit -m "Update configuration" -S >/dev/null 2>&1 &&
                        git push >/dev/null 2>&1)) &
return 0
